### ISSUE TITLE
Workaround for strawberry

### ISSUE THREAD

**Issue by huyz** [jhnnsrs/turms#42]
I'm trying to make a Strawberry API out of Pydantic classes generated by turms using the experimental https://strawberry.rocks/docs/integrations/pydantic support.

But I'm getting:
```
TypeError: GetExternalRunsResult fields cannot be resolved. Unexpected type 'typing.Literal['ExternalRun']'
```
 which I think is the same problem as: https://github.com/strawberry-graphql/strawberry/issues/2317

Any idea for a workaround?

**Comment by huyz** [comment]
Well, I basically commented out the line in `turms` that outputs `typename`

**Comment by jhnnsrs** [comment]
I am not entirely sure if i understand your use case:

Is it a schema first approach where you want to generate pydantic models from a graphql schema and then translate that to strawberry types and potentially queries?

Because if so, i don't think the plugins reflect that use case too well at this point. As the models generated with the object plugin would generate 'self referencing ' fields (referencing other models not IDs). I'll dive into the strawberry documentation to maybe see if it makes sense to adapt it as a strawberry plugin.

I am still wondering why to use pydantic for the objects and queries in the first place on the backend? You wouldn't really need it's capabilities for validation there (besides for inputtypes) as the backend is supposedly the source of truth. Or is it for runtime type safety and dev experience?

Would it be better for your use case to have strawberry types generated directly from the schema? 

Hope i made myself understandable, and looking forward for your feedback!

**Comment by huyz** [comment]
Thank you for following up!

> I am still wondering why to use pydantic for the objects and queries in the first place on the backend? You wouldn't really need it's capabilities for validation there (besides for inputtypes) as the backend is supposedly the source of truth. Or is it for runtime type safety and dev experience?

Very good question, and I appreciate your bringing up all these points as they help me solidify my thinking.

I'm still trying to figure out the architecture of the layers that I'm responsible for: (1) python client, and (2) the key middle layer (which is both a server to that client and a client to a pre-existing GraphQL API running on another host). And most of the tools and libraries and frameworks I'm using now are new to me, including Chalice, Strawberry, Pydantic, and Turms.  So this is very subject to change and I welcome any feedback.
But let me try to share my current thoughts.

As I mentioned I'm mainly focused on the middle layer.  What I wanted to do first is to try to cover all bases before actually figuring out if there are pieces that are unnecessary:
1. Generate pydantic classes from the introspected GraphQL schema running on the remote host, which would allow me to (1) properly validate & type any data that would corresponding to inputtypes for the remote host (as you said) and (2), as for values returned from the remote host, give me automatic type hints so that I don't need to write validation code, guards, unit tests, and casts to python types as my IDE (and mypy) can catch issues automatically (as you said).
2. Well, now that I have Pydantic types, I can selectively expose a new GraphQL API, that is a filtered subset of the pre-existing GraphQL api and can include new operations and types only known to this middle layer.  Strawberry has an experimental feature that does just that: provide helpers to facilitate exposing a GraphQL API based on pydantic types (still requires some manual conversion code so it's not automatic).  And Strawberry also is easily integrated in Chalice. 

Right now, this middle layer serves a REST API to the client, and I'm playing around with how much to move to a GraphQL API, how much to keep in REST.  With the setup I'm trying, (1) I can receive REST and GraphQL requests from the client and (2) I can do GraphQL in both directions—serving and as a client. 

As you also suggested with "runtime type safety", maybe these Pydantic classes can now help me do run-time validation for the data coming in through the REST endpoints (while GraphQL already automatically does that for me—right?).  I would of course add new Pydantic classes for objects only known to this middle layer.

What do you think?

**Comment by jhnnsrs** [comment]
Thats a very interesting use case , and made me realize a few new use cases for turms that i will put in the documentation. I will try to illustrate on the example of your middle layer what are my thoughts on "turms for api gateway generation". 

First a few general thoughts and assumptions that i am making:
1. I assume that the final graphql server (the last in the chain) represent some kind of third party api that has a non changeable schema.
2. The client you are writing in python should only speak to the middleman, gateway server, that may have some additional functionality exposed via REST. 
3. The middleman api is not to be used as a generalized "third party app", e.g tighter coupling between the python client and this middleman api is not a problem.

My solution:
If that is the case I maybe wouldn't implement a GraphQL API on the middleman at all but rather expose a REST api that would in turn call the GraphQL API of the final api server. The implementation i would choose would involve using turms to generate code for specific operations on the GraphQL API and expose them as Rest API. I am not to familiar with Chalice but i would experiment with FastAPI that is able to generate restful endpoints from pydantic types quite easily. With the funcs plugin (haven't tried it though) you should be able to generate code from an operation like this:

````graphql

query third_party_query($id: ID) {
    endpoint(id: $id) {
       field
       field_two {
          subfield
       }
  }
}
````

run turms gen to generate the operations and functions for the middleman, and then have a fast api exposed like this

````python
from fastapi import FastAPI
from generated import athird_party_query, athird_party_mutation

app = FastAPI()


app.get("/third_party_query/{id}")(athird_party_query)
app.post("/third_party_mutation/)(athird_party_mutation)

````
Because fast api can read the function parameters (including the pydantic input types) you would get a nice
open api schema for your graphql schema (best of both world i guess :D). Also most importantly this enables operation
level caching, rate limiting etc through fast api, which can otherwise be very annoying with pure graphql apis. You could then
easily generate also other RESTful endpoints.


The same generated function could then also be used for the python code on the client but in turn not calling the graphql api of the third party server but making requests to your api gateway. (simply by replacing the proxy function with a call to your restful api).


````python
from generation import athird_party_query

async with Rath():
       x = athird_party_query()
````

This would be my general solution to the problem:  (I will put something like this as an example in the documentation, thanks for bringing up :))

This case however would not include setting up a GraphQL endpoint on the middleman. If you still want that, a few words on what you might also have to consider:

Generally a big benefit of graphql is avoiding overfetching, however if you proxy a service you need to be very considerate on how you want to handle forwarding the graphql request (e.g avoiding to fetch fields on the proxy query if the first query doesnt need to include these fields). Personally i would rather choose something like Apollo Federation that would help you with merging the schema. 

Hope this helps? :)

**Comment by jhnnsrs** [comment]
Got a chance to talk to patrick of strawberry in:
https://github.com/strawberry-graphql/strawberry/issues/2400
and 
https://discord.com/channels/689806334337482765/1038398995199954974

Which is leading to #44 

:)

**Comment by jhnnsrs** [comment]
#44 closes this
